### ISSUE TITLE
Python error str and None

### ISSUE THREAD

**Issue by anance25** [MarkoH17/Spray365#7] opened 2022-05-27 16:24 UTC
Ubuntu 20.04
Python 3.8.10

Running into this issue when attempting to run spray365.

```
$ python3 spray365.py

Traceback (most recent call last):
  File "spray365.py", line 2, in <module>
    from modules.core.output import console
  File "/home/nancea/Spray365/modules/core/output/console.py", line 74, in <module>
    line_terminator: str | None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

EDIT to fix formatting

**Comment by MarkoH17** [comment] 2022-05-27 17:08
This is caused by [Python versions < 3.10](https://docs.python.org/3/whatsnew/3.10.html#types) not having the `NoneType` type constant. 

I'll update the README to indicate Python3.10 is the recommended version. 

And in the meantime, I'll add a patch to support our type checking that causes this issue in older Python versions.

**Comment by MarkoH17** [comment] 2022-05-27 17:17
@anance25 ,

This should be fixed in f475f73e421eec302629a55eaef4295f481caf8e. Can you pull the latest version and retry?

**Comment by anance25** [comment] 2022-05-27 19:55
@MarkoH17 i wasn't sure from your comment if i should pull again and try with 3.8.10, but i did.  Slightly different error this time:

```
$ python3 spray365.py

Traceback (most recent call last):
  File "spray365.py", line 3, in <module>
    from modules.generate import generate
  File "/home/nancea/Spray365/modules/generate/generate.py", line 2, in <module>
    from modules.generate.modes import audit, normal
  File "/home/nancea/Spray365/modules/generate/modes/audit.py", line 9, in <module>
    from modules.core.credential import Credential
  File "/home/nancea/Spray365/modules/core/credential.py", line 1, in <module>
    class Credential:
  File "/home/nancea/Spray365/modules/core/credential.py", line 7, in Credential
    client_id: tuple[str, str],
TypeError: 'type' object is not subscriptable
```

I ended up installing 3.10 from ppa on this ubuntu 20.04 box i was using and now its working.  Again, not sure if the intent was to get versions as old as 3.8 working, but thanks for clarifying what was needed.  You might also mention in the readme that ubuntu 20.04 does not want to work with python 3.10 out of the box, and it took some elbow grease to get that working.

**Comment by MarkoH17** [comment] 2022-05-27 19:58
@anance25,

My mistake! I thought I read you were using Python 3.9, so I intended to get it working for that version. I guess it is reasonable to try to get this working for Python 3.8, so I'll see what I can do about that. 

Thanks for helping out with this. I'll circle back when I've made some progress.

**Comment by MarkoH17** [comment] 2022-06-01 18:36
@anance25,

Spray365 version 0.2.1-beta was released today. As of 20b8d2b356c53c4268e1f7c74d416e9a1dfef360, Spray365 should run in older Python 3 environments (3.7+). Can you pull the latest release and see if it works in your Python 3.8.10 environment?

**Comment by MarkoH17** [comment] 2022-06-14 14:51
Just tested Spray365 v0.2.1-beta on Python 3.8.13, and it appears functional. 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/8473031/173607895-f699e1cf-c0ed-4177-834b-ce273d17c3b4.png">

Closing this issue for now. Feel free to open a new one if you see any more compatibility issues.

**Closed as completed by MarkoH17** 2022-06-14 14:51 UTC
